const { COMMANDS } = require('../constants/index');
const { myDataHandler } = require("./private/myDataHandler");
const { editProfileHandler } = require("./private/editProfileHandler");
const { handleChangeName } = require("./private/handleChangeName");
const { handleChangeWBId } = require("./private/handleChangeWBId");
const { handleUnsubscribeSettings } = require("./private/handleUnsubscribeSettings");
const { handleAddPVZForRequest } = require("./private/handleAddPVZForRequest");
const { handleDeletePVZForRequest } = require("./private/handleDeletePVZForRequest");
const { handleAddReplacement } = require("./private/handleAddReplacement");
const { handledeleteReplacement } = require("./private/handleDeletedAReplacement");
const { handleListPvz } = require("./admin/handleListPVZ");
const { handleAdminMenu } = require("./admin/handleAdminMenu");
const { handleChatReport } = require("./handleChatReport");
const { handleAddPVZ } = require("./admin/handleAddPVZ");
const { handleDeletePVZ } = require("./admin/handleDeletePVZ");
const { handleUnsubscriptions } = require("./admin/handleUnsubscriptions");
const { handleTheyWillReturn } = require("./admin/handleTheyWillReturn");
const { handlePVZOpeningReport } = require("./admin/handlePVZOpeningReport");
const { handlePVZClosureReport } = require("./admin/handlePVZClosureReport");
const { handleThereIsNoOpeningReport } = require("./admin/handleThereIsNoOpeningReport");
const { handleThereIsNoClosesReport } = require('./admin/handleThereIsNoClosesReport');
const { handleToRemindAboutTheOpening } = require('./admin/handleToRemindAboutTheOpening');
const { handleToRemindAboutTheCloses } = require('./admin/handleToRemindAboutTheCloses');

const commandHandlers = {
  [COMMANDS.MY_DATA]: (senderId) => myDataHandler(senderId),
  [COMMANDS.EDIT_DATA]: (senderId) => editProfileHandler(senderId),
  [COMMANDS.CHANGE_NAME]: (senderId) => handleChangeName(senderId),
  [COMMANDS.CHANGE_WB_ID]: (senderId) => handleChangeWBId(senderId),
  [COMMANDS.UNSUBSCRIBE_SETTINGS]: (senderId) => handleUnsubscribeSettings(senderId),
  [COMMANDS.ADD_PVZ]: (senderId) => handleAddPVZForRequest(senderId),
  [COMMANDS.DELETE_PVZ]: (senderId) => handleDeletePVZForRequest(senderId),
  [COMMANDS.ADD_REPLACEMENT]: (senderId) => handleAddReplacement(senderId),
  [COMMANDS.DELETE_REPLACEMENT]: (senderId) => handledeleteReplacement(senderId),
  [COMMANDS.BACK]: (senderId) => myDataHandler(senderId),
  [COMMANDS.ADMIN]: (senderId) => handleAdminMenu(senderId),
  [COMMANDS.OPEN_PVZ]: (senderId) => handleChatReport(senderId, "open"),
  [COMMANDS.CLOSE_PVZ]: (senderId) => handleChatReport(senderId, "close"),
  [COMMANDS.ADD_PVZ_TO_DB]: (senderId, isAdmin) => handleAddPVZ(senderId, isAdmin),
  [COMMANDS.DELETE_PVZ_FROM_DB]: (senderId, isAdmin) => handleDeletePVZ(senderId, isAdmin),
  [COMMANDS.LIST_PVZ]: (senderId, isAdmin) => handleListPvz(senderId, isAdmin),
  [COMMANDS.UNSUBSCRIPTIONS_MENU]: (senderId, isAdmin) => handleUnsubscriptions(senderId, isAdmin),
  [COMMANDS.BACK_TO_ADMIN]: (senderId, isAdmin) => handleTheyWillReturn(senderId, isAdmin),
  [COMMANDS.REPORT_OPENING]: (senderId, isAdmin) => handlePVZOpeningReport(senderId, isAdmin),
  [COMMANDS.REPORT_CLOSING]: (senderId, isAdmin) => handlePVZClosureReport(senderId, isAdmin),
  [COMMANDS.MISSING_OPENING]: (senderId, isAdmin) => handleThereIsNoOpeningReport(senderId, isAdmin),
  [COMMANDS.MISSING_CLOSING]: (senderId, isAdmin) => handleThereIsNoClosesReport(senderId, isAdmin),
  [COMMANDS.REMIND_OPENING]: (senderId, isAdmin) => handleToRemindAboutTheOpening(senderId, isAdmin),
  [COMMANDS.REMIND_CLOSING]: (senderId, isAdmin) => handleToRemindAboutTheCloses(senderId, isAdmin),
};

module.exports = { commandHandlers };
